#ifndef MBEDTLS_APP_CONFIG_H
#define MBEDTLS_APP_CONFIG_H

#undef MBEDTLS_AES_C
#undef MBEDTLS_CIPHER_C
#undef MBEDTLS_CHACHA20_C
#undef MBEDTLS_POLY1305_C
#undef MBEDTLS_GCM_C
#undef MBEDTLS_CCM_C

#endif /* MBEDTLS_APP_CONFIG_H */
