# --- Console ---
CONFIG_PRINTK=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# --- Stack Réseau CO-EXISTANTE (Zephyr IPv6 + Nanostack) ---
CONFIG_NETWORKING=y
CONFIG_NANOSTACK=y
CONFIG_NET_NATIVE=y

# --- Pont Radio L2 (Spécifique Radio) ---
CONFIG_NANOSTACK_BRIDGE_RADIO=y
CONFIG_IEEE802154=y
CONFIG_NET_L2_IEEE802154=y
CONFIG_NET_CONFIG_IEEE802154_CHANNEL=0
CONFIG_NET_CONFIG_IEEE802154_PAN_ID=0x1234
CONFIG_NET_IPV6=n
CONFIG_NET_ARP=n
CONFIG_NET_IPV4=n
CONFIG_NET_PROMISCUOUS_MODE=y
CONFIG_NET_BUF=y

# --- Sockets ---
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_PACKET=y
CONFIG_NET_PKT_FILTER=y

# --- Demander à Zephyr d'appliquer une configuration réseau au boot ---
CONFIG_NET_CONFIG_SETTINGS=y

# --- Configuration explicite des slots de connexion ---
CONFIG_NET_MAX_CONN=10
CONFIG_NET_MAX_CONTEXTS=10

# --- mbedTLS Réglages Réseau & Entropie ---
CONFIG_MBEDTLS=y
CONFIG_MBEDTLS_BUILTIN=y
CONFIG_MBEDTLS_PSA_CRYPTO_C=y
CONFIG_MBEDTLS_MD_C=y
CONFIG_PSA_WANT_KEY_TYPE_AES=y


# Allocation mémoire optimisée pour mbedTLS
CONFIG_MBEDTLS_ENABLE_HEAP=y
CONFIG_MBEDTLS_HEAP_SIZE=4096

# --- Optimisations Espace Flash ---
CONFIG_SIZE_OPTIMIZATIONS=y

# --- Configuration Mémoire Générale ---
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=1024
